version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    groups:
      development-dependencies:
        dependency-type: development
